TITEL_METADATA = {
    # Akademische Titel (Top 20)
    "Dr.": {"geschlecht": "unisex", "nationalitaet": "DE"},
    "Prof.": {"geschlecht": "unisex", "nationalitaet": "DE"},
    "Professor": {"geschlecht": "männlich", "nationalitaet": "DE"},
    "Professorin": {"geschlecht": "weiblich", "nationalitaet": "DE"},
    "Dipl.-Ing.": {"geschlecht": "unisex", "nationalitaet": "DE"},
    "Dr.-Ing.": {"geschlecht": "unisex", "nationalitaet": "DE"},
    "Dr. med.": {"geschlecht": "unisex", "nationalitaet": "DE"},
    "Dr. jur.": {"geschlecht": "unisex", "nationalitaet": "DE"},
    "Dr. phil.": {"geschlecht": "unisex", "nationalitaet": "DE"},
    "Dr. theol.": {"geschlecht": "unisex", "nationalitaet": "DE"},
    "Dr. rer. nat.": {"geschlecht": "unisex", "nationalitaet": "DE"},
    "Dr. h.c.": {"geschlecht": "unisex", "nationalitaet": "DE"},
    "Dr. h.c. mult.": {"geschlecht": "unisex", "nationalitaet": "DE"},
    "Univ.-Prof.": {"geschlecht": "unisex", "nationalitaet": "DE"},
    "PD": {"geschlecht": "unisex", "nationalitaet": "DE"},
    "Dipl.-Kfm.": {"geschlecht": "unisex", "nationalitaet": "DE"},
    "Dipl.-Volksw.": {"geschlecht": "unisex", "nationalitaet": "DE"},
    "M.Sc.": {"geschlecht": "unisex", "nationalitaet": "DE"},
    "B.Sc.": {"geschlecht": "unisex", "nationalitaet": "DE"},
    "MBA": {"geschlecht": "unisex", "nationalitaet": "DE"},

    # Adelstitel (Top 20 + Monarchen)
    "Freiherr": {"geschlecht": "männlich", "nationalitaet": "DE"},
    "Freifrau": {"geschlecht": "weiblich", "nationalitaet": "DE"},
    "Baron": {"geschlecht": "männlich", "nationalitaet": "DE"},
    "Baronin": {"geschlecht": "weiblich", "nationalitaet": "DE"},
    "Graf": {"geschlecht": "männlich", "nationalitaet": "DE"},
    "Gräfin": {"geschlecht": "weiblich", "nationalitaet": "DE"},
    "Fürst": {"geschlecht": "männlich", "nationalitaet": "DE"},
    "Fürstin": {"geschlecht": "weiblich", "nationalitaet": "DE"},
    "Herzog": {"geschlecht": "männlich", "nationalitaet": "DE"},
    "Herzogin": {"geschlecht": "weiblich", "nationalitaet": "DE"},
    "Prinz": {"geschlecht": "männlich", "nationalitaet": "DE"},
    "Prinzessin": {"geschlecht": "weiblich", "nationalitaet": "DE"},
    "Markgraf": {"geschlecht": "männlich", "nationalitaet": "DE"},
    "Markgräfin": {"geschlecht": "weiblich", "nationalitaet": "DE"},
    "Landgraf": {"geschlecht": "männlich", "nationalitaet": "DE"},
    "Landgräfin": {"geschlecht": "weiblich", "nationalitaet": "DE"},
    "Kurfürst": {"geschlecht": "männlich", "nationalitaet": "DE"},
    "Kurfürstin": {"geschlecht": "weiblich", "nationalitaet": "DE"},
    "Edler": {"geschlecht": "männlich", "nationalitaet": "DE"},
    "Edle": {"geschlecht": "weiblich", "nationalitaet": "DE"},
    "König": {"geschlecht": "männlich", "nationalitaet": "DE"},
    "Königin": {"geschlecht": "weiblich", "nationalitaet": "DE"},
    "Kaiser": {"geschlecht": "männlich", "nationalitaet": "DE"},
    "Kaiserin": {"geschlecht": "weiblich", "nationalitaet": "DE"},
    "Erzherzog": {"geschlecht": "männlich", "nationalitaet": "DE"},
    "Erzherzogin": {"geschlecht": "weiblich", "nationalitaet": "DE"},
    "Thronfolger": {"geschlecht": "männlich", "nationalitaet": "DE"},
    "Thronfolgerin": {"geschlecht": "weiblich", "nationalitaet": "DE"}
}

SALUTATIONS = {
    "Herr": {"geschlecht": "männlich", "nationalitaet": "DE"},
    "Frau": {"geschlecht": "weiblich", "nationalitaet": "DE"},
    "Mrs.": {"geschlecht": "weiblich", "nationalitaet": "EN"},
    "Mr.": {"geschlecht": "männlich", "nationalitaet": "EN"},
    "Mme.": {"geschlecht": "weiblich", "nationalitaet": "FR"},
    "M.": {"geschlecht": "männlich", "nationalitaet": "FR"},
    "Señora": {"geschlecht": "weiblich", "nationalitaet": "ES"},
    "Señor": {"geschlecht": "männlich", "nationalitaet": "ES"},
}
