TITEL_METADATA = {
    # Akademische Titel
    "Dr.": {"geschlecht": "unisex", "nationalitaet": "DE"},
    "Prof.": {"geschlecht": "unisex", "nationalitaet": "DE"},
    "Professor": {"geschlecht": "männlich", "nationalitaet": "DE"},
    "Professorin": {"geschlecht": "weiblich", "nationalitaet": "DE"},
    "Dipl.-Ing.": {"geschlecht": "unisex", "nationalitaet": "DE"},
    "Dr.-Ing.": {"geschlecht": "unisex", "nationalitaet": "DE"},
    "Dr. h.c. mult.": {"geschlecht": "unisex", "nationalitaet": "DE"},
    "Dr. rer. nat.": {"geschlecht": "unisex", "nationalitaet": "DE"},
    "Dr. med.": {"geschlecht": "unisex", "nationalitaet": "DE"},
    "Dr. jur.": {"geschlecht": "unisex", "nationalitaet": "DE"},
    "Dr. phil.": {"geschlecht": "unisex", "nationalitaet": "DE"},
    "Dr. rer. pol.": {"geschlecht": "unisex", "nationalitaet": "DE"},
    "Dr. theol.": {"geschlecht": "unisex", "nationalitaet": "DE"},
    "Dr. paed.": {"geschlecht": "unisex", "nationalitaet": "DE"},
    "Dr. habil.": {"geschlecht": "unisex", "nationalitaet": "DE"},
    "Dr. rer. oec.": {"geschlecht": "unisex", "nationalitaet": "DE"},
    "Dr. rer. soc.": {"geschlecht": "unisex", "nationalitaet": "DE"},
    "Dr. h. c.": {"geschlecht": "unisex", "nationalitaet": "DE"},
    "Dipl.-Kfm.": {"geschlecht": "unisex", "nationalitaet": "DE"},
    "Dipl.-Volksw.": {"geschlecht": "unisex", "nationalitaet": "DE"},
    "M.Sc.": {"geschlecht": "unisex", "nationalitaet": "DE"},
    "B.Sc.": {"geschlecht": "unisex", "nationalitaet": "DE"},

    # Adels-/Monarchentitel
    "Kaiser": {"geschlecht": "männlich", "nationalitaet": "DE"},
    "Kaiserin": {"geschlecht": "weiblich", "nationalitaet": "DE"},
    "König": {"geschlecht": "männlich", "nationalitaet": "DE"},
    "Königin": {"geschlecht": "weiblich", "nationalitaet": "DE"},
    "Erzherzog": {"geschlecht": "männlich", "nationalitaet": "DE"},
    "Erzherzogin": {"geschlecht": "weiblich", "nationalitaet": "DE"},
    "Großherzog": {"geschlecht": "männlich", "nationalitaet": "DE"},
    "Großherzogin": {"geschlecht": "weiblich", "nationalitaet": "DE"},
    "Kurfürst": {"geschlecht": "männlich", "nationalitaet": "DE"},
    "Kurfürstin": {"geschlecht": "weiblich", "nationalitaet": "DE"},
    "Fürst": {"geschlecht": "männlich", "nationalitaet": "DE"},
    "Fürstin": {"geschlecht": "weiblich", "nationalitaet": "DE"},
    "Herzog": {"geschlecht": "männlich", "nationalitaet": "DE"},
    "Herzogin": {"geschlecht": "weiblich", "nationalitaet": "DE"},
    "Markgraf": {"geschlecht": "männlich", "nationalitaet": "DE"},
    "Markgräfin": {"geschlecht": "weiblich", "nationalitaet": "DE"},
    "Landgraf": {"geschlecht": "männlich", "nationalitaet": "DE"},
    "Landgräfin": {"geschlecht": "weiblich", "nationalitaet": "DE"},
    "Pfalzgraf": {"geschlecht": "männlich", "nationalitaet": "DE"},
    "Pfalzgräfin": {"geschlecht": "weiblich", "nationalitaet": "DE"},
    "Graf": {"geschlecht": "männlich", "nationalitaet": "DE"},
    "Gräfin": {"geschlecht": "weiblich", "nationalitaet": "DE"},
    "Freiherr": {"geschlecht": "männlich", "nationalitaet": "DE"},
    "Freifrau": {"geschlecht": "weiblich", "nationalitaet": "DE"},
    "Freifräulein": {"geschlecht": "weiblich", "nationalitaet": "DE"},
    "Baron": {"geschlecht": "männlich", "nationalitaet": "DE"},
    "Baronin": {"geschlecht": "weiblich", "nationalitaet": "DE"},
    "Edler": {"geschlecht": "männlich", "nationalitaet": "DE"},
    "Edle": {"geschlecht": "weiblich", "nationalitaet": "DE"},
    "Prinz": {"geschlecht": "männlich", "nationalitaet": "DE"},
    "Prinzessin": {"geschlecht": "weiblich", "nationalitaet": "DE"}, 
    "Thronfolger": {"geschlecht": "männlich", "nationalitaet": "DE"},
    "Thronfolgerin": {"geschlecht": "weiblich", "nationalitaet": "DE"}
}

SALUTATIONS = {
    "Herr": {"geschlecht": "männlich", "nationalitaet": "DE"},
    "Frau": {"geschlecht": "weiblich", "nationalitaet": "DE"},
    "Mrs.": {"geschlecht": "weiblich", "nationalitaet": "EN"},
    "Mr.": {"geschlecht": "männlich", "nationalitaet": "EN"},
    "Mme.": {"geschlecht": "weiblich", "nationalitaet": "FR"},
    "M.": {"geschlecht": "männlich", "nationalitaet": "FR"},
    "Señora": {"geschlecht": "weiblich", "nationalitaet": "ES"},
    "Señor": {"geschlecht": "männlich", "nationalitaet": "ES"},
}

LASTNAME_PREFIXES= {"von", "van", "de", "del", "di", "le", "la", "du"}
